### ISSUE TITLE
Installation instructions provide wrong path

### ISSUE THREAD

**Issue by sao-cem** [kevgrig/linuxdoddns#1]
First line should be:

1. `sudo git clone https://github.com/kevgrig/linuxdoddns /opt/linuxdodns`

not

1. `sudo git clone https://github.com/kevgrig/linuxdoddns /opt/linuxdoddns`

The services are looking for one less d.

**Comment by kevgrig** [comment]
Oops! I've updated all scripts and occurrences of `linuxdodns` with `linuxdoddns` (with the extra `d` for "dynamic"). Thank you.
